apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    db: frontenddb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: frontenddb
  template:
    metadata:
      labels:
        db: frontenddb
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongo"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "mongo"

        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
      
      volumes:
      - name: mongodb-data
        hostPath:
          path: /mnt/nfs/mongodb_data/
          type: Directory

